Subject: Ayons asperges pour le =?utf-8?q?d=C3=A9jeuner?=
From: =?utf-8?q?Pep=C3=A9?= Le Pew <pepe@example.com>
To: rohancroma@gmail.com
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="===============0993425017=="

--===============0993425017==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

Salut!

Cela ressemble à un excellent recipie[1] déjeuner.

[1] http://www.yummly.com/recipe/Roasted-Asparagus-Epicurious-203718

--Pepé

--===============0993425017==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<html>
  <head></head>
  <body>
    <p>Salut!</p>
    <p>Cela ressemble =C3=A0 un excellent
        <a href=3D"http://www.yummly.com/recipe/Roasted-Asparagus-Epicurious-=
203718">
            recipie
        </a> d=C3=A9jeuner.
    </p>   =20
  </body>
</html>

--===============0993425017==--
